[package]
name = "dsrv"
version = "0.1.0"
authors = ["Chris P <chrisp1877@gmail.com>"]
edition = "2018"
default_run = "main"

[lib]
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
url = "*"
crossbeam-channel = "*"
ipnetwork = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
dpool = { path = "./dpool" }
dargs = { path = "./dargs" }
dhttp = { path = "./dhttp" }

[dev-dependencies]
criterion = "*"
env_logger = "*"

# [build-dependencies]
# protoc-rust-grpc = "*"

[profile.dev]
opt="z"
